Feature/informar reserva
desenvolvendo-me/tem_acai pull request #79
Opened 2021-06-09 09:10 UTC by diegoshakan

2021-06-09 09:11 UTC, diegoshakan commented
@Pauloparakleto poderia dar uma olhada em como poderia resolver o problema de duas métricas que o Rubocop está apontando?
1. Muitos argumentos no initialize
2. Classe com mais de 100 linhas

2021-06-09 09:27 UTC, Pauloparakleto commented
Uma saída é passar args* ou options para acessar a hash de options na inicialização.

2021-06-09 09:29 UTC, Guih12 requested changes
remove conflicts

2021-06-09 09:29 UTC, Pauloparakleto commented
Sobre o group together all attr_writer, seria: `attr_writer: :attribute_a, :attribute_b`

2021-06-09 22:44 UTC, Pauloparakleto commented
Resolvido a ofensa de muitas linhas. Resta ainda a de muitos parâmetros na inicialização. Continuemos...

2021-06-10 00:40 UTC, Pauloparakleto commented
@diegoshakan e @Guih12 analisem o que foi feito. Caso este Pr seja aceito, precisaremos reabrir em torno de duas issues da release 3 e colocá-las no backlog. A meu ver, chegou-se a um ponto em que o débito técnico nos fez pagar o preço. São as issues referentes aos testes que precisei ignorar para avançar aqui.

2021-06-10 11:18 UTC, Pauloparakleto commented
Atualizado com a Release após rebase e resolução de conflitos.

2021-06-10 23:17 UTC, Pauloparakleto commented
@marcodotcastro   [Heckle](https://ruby.sadi.st/Heckle.html) é uma sugestão do Rubycritic para colocar os testes à prova. Preciso de ajuda para instalar. Ele aparece como sugestão nos "cheiros" de Highcomplexity de `company_spec.rb`

2021-06-10 23:27 UTC, marcodotcastro commented
> @marcodotcastro   [Heckle](https://ruby.sadi.st/Heckle.html) é uma sugestão do Rubycritic para colocar os testes à prova. Preciso de ajuda para instalar. Ele aparece como sugestão nos "cheiros" de Highcomplexity de `company_spec.rb`

É uma boa prática verifica o suporte de gem antes de adicionar à um projeto.

Verifique como está a manutenção da gem e me diga se vale a pena colocá-la ao projeto? Porque do sim ou não?

2021-06-11 23:54 UTC, merged